// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovimentosManuais.InfraStruture.Data;

namespace MovimentosManuais.InfraStruture.Migrations
{
    [DbContext(typeof(MovimentosManuaisContext))]
    [Migration("20220510025231__migration001")]
    partial class _migration001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovimentosManuais.ApplicationCore.Entity.Movimento_Manual", b =>
                {
                    b.Property<string>("COD_COSIF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("CHAR(11)");

                    b.Property<string>("COD_PRODUTO")
                        .IsRequired()
                        .HasColumnType("CHAR(4)");

                    b.Property<string>("COD_USUARIO")
                        .HasColumnType("VARCHAR(15)");

                    b.Property<decimal>("DAT_ANO")
                        .HasColumnType("NUMERIC(4,0)");

                    b.Property<decimal>("DAT_MES")
                        .HasColumnType("NUMERIC(2,0)");

                    b.Property<DateTime>("DAT_MOVIMENTO")
                        .HasColumnType("SMALLDATETIME");

                    b.Property<string>("DES_DESCRICAO")
                        .IsRequired()
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal>("NUM_LANCAMENTO")
                        .HasColumnType("NUMERIC(18,0)");

                    b.Property<string>("Produto_CosifCOD_PRODUTO");

                    b.Property<decimal>("VAL_VALOR")
                        .HasColumnType("NUMERIC(18,2)");

                    b.HasKey("COD_COSIF");

                    b.HasAlternateKey("COD_PRODUTO");

                    b.HasAlternateKey("DAT_ANO");

                    b.HasAlternateKey("DAT_MES");

                    b.HasAlternateKey("NUM_LANCAMENTO");

                    b.HasIndex("Produto_CosifCOD_PRODUTO");

                    b.ToTable("MOVIMENTO_MANUAL");
                });

            modelBuilder.Entity("MovimentosManuais.ApplicationCore.Entity.Produto", b =>
                {
                    b.Property<string>("COD_PRODUTO")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("DES_PRODUTO")
                        .IsRequired()
                        .HasColumnType("VARCHAR(30)");

                    b.Property<string>("STA_STATUS")
                        .IsRequired()
                        .HasColumnType("CHAR(1)");

                    b.HasKey("COD_PRODUTO");

                    b.ToTable("PRODUTO");
                });

            modelBuilder.Entity("MovimentosManuais.ApplicationCore.Entity.Produto_Cosif", b =>
                {
                    b.Property<string>("COD_PRODUTO")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("COD_CLASSIFICACAO")
                        .IsRequired()
                        .HasColumnType("CHAR(6)");

                    b.Property<string>("COD_COSIF")
                        .IsRequired()
                        .HasColumnType("CHAR(11)");

                    b.Property<string>("ProdutoCOD_PRODUTO");

                    b.Property<string>("STA_STATUS")
                        .IsRequired()
                        .HasColumnType("CHAR(1)");

                    b.HasKey("COD_PRODUTO");

                    b.HasAlternateKey("COD_COSIF");

                    b.HasIndex("ProdutoCOD_PRODUTO");

                    b.ToTable("PRODUTO_COSIF");
                });

            modelBuilder.Entity("MovimentosManuais.ApplicationCore.Entity.Movimento_Manual", b =>
                {
                    b.HasOne("MovimentosManuais.ApplicationCore.Entity.Produto_Cosif")
                        .WithMany("Contatos")
                        .HasForeignKey("Produto_CosifCOD_PRODUTO");
                });

            modelBuilder.Entity("MovimentosManuais.ApplicationCore.Entity.Produto_Cosif", b =>
                {
                    b.HasOne("MovimentosManuais.ApplicationCore.Entity.Produto")
                        .WithMany("Produto_Cosifs")
                        .HasForeignKey("ProdutoCOD_PRODUTO");
                });
#pragma warning restore 612, 618
        }
    }
}
